### ISSUE TITLE
Bug in judy-fk, core dump if 

### ISSUE THREAD

**Issue by dougbaskins** [qiq/judy-fk#1]
JudyLSFK.c is broken.  Will core dump if these 3 strings are input:

NETWORKVISIONARIES.NET
NETWORKVAULT.COM
NETWORKVISIONARIE

Problem is a design fault and I suspect cannot be fixed without
a design change.  I was really hoping this code would work.
If it would be a good replacement for JudyHS.c, which I never
completed.

Doug Baskins
dougbaskins@yahoo.com

**Comment by dougbaskins** [comment]
I forgot, the Value areas must me non-zero.  The problem is the tree search will not terminate
soon enough and continue as if the value area is a pointer to the next JudyL array.  If the Value
area is non-null, then a dereference will be done on the "Value, thus causing a core dump.
doug.

**Comment by dougbaskins** [comment]
I am new to github, cannot figure how to posr.

**Comment by qiq** [comment]
judy-fk library is intended to be used with all keys sharing the same fixed length (len parameter must be the same for all keys). The library interface is not ideal, the intention was to keep it as similar to the original Judy SL library interface as possible.

From your bugreport it seems that you are trying to insert keys of different lengths, which is the cause of the error reported. If not, please show the code that is causing the library to crash.

**Comment by dougbaskins** [comment]
Miroslav:
You are absolutely correct, I was using keys of different lengths.  I figured out laterwhat FK meant.  I was not able to find a "man" page on the web, which is why ittook me longer than it should of.
Thanks for your interest,
doug
Doug Baskins <dougbaskins@yahoo.com>
P.S.  I am working on a yet -to-be-named version of Judy where you specifythe Key length, the Value area length (per Key) and the sort order (Dictionary or Numeric)It will allow embedded null characters in the keys.  Any thoughts on the API or whateverwill be appreciated.
 

    On Sunday, January 22, 2017 2:45 PM, Miroslav Spousta <notifications@github.com> wrote:
 
 

 judy-fk library is intended to be used with all keys sharing the same fixed length (len parameter must be the same for all keys). The library interface is not ideal, the intention was to keep it as similar to the original Judy SL library interface as possible.From your bugreport it seems that you are trying to insert keys of different lengths, which is the cause of the error reported. If not, please show the code that is causing the library to crash.—

**Comment by qiq** [comment]
OK, thanks for clarification.
